/* eslint-disable @next/next/no-img-element */
"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect,useMemo,useState,type ChangeEvent } from "react";
import { adminApiBase,adminFetch } from "@/lib/adminApi";

type Status="draft"|"published"|"hidden";type Extra={id?:string;type:"image"|"audio"|"video"|"text";file_key:string;file_url?:string;title_zh:string;title_en:string;caption_zh:string;caption_en:string;recorded_at:string;sort_order:number;status:Status;uploadStatus?:string};
type Form={id?:string;slug:string;original_title:string;title_zh:string;title_en:string;language:""|"zh"|"en"|"mixed";completed_at:string;summary_zh:string;summary_en:string;shelf_order:number;status:Status;lyrics_original:string;lyrics_zh:string;lyrics_en:string;cover_key:string;audio_key:string;cover_url?:string;audio_url?:string;extras:Extra[]};
const blank:Form={slug:"",original_title:"",title_zh:"",title_en:"",language:"",completed_at:"",summary_zh:"",summary_en:"",shelf_order:0,status:"draft",lyrics_original:"",lyrics_zh:"",lyrics_en:"",cover_key:"",audio_key:"",extras:[]};
const newExtra=():Extra=>({type:"text",file_key:"",title_zh:"",title_en:"",caption_zh:"",caption_en:"",recorded_at:"",sort_order:0,status:"draft"});
const lineCount=(v:string)=>v.replace(/\r\n/g,"\n").split("\n").length;
export default function SongForm(){
 const params=useSearchParams(),id=params.get("id"),[form,setForm]=useState<Form>(blank),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const lyricWarning=useMemo(()=>{const c=[lineCount(form.lyrics_original),lineCount(form.lyrics_zh),lineCount(form.lyrics_en)];return c.every(x=>x===c[0])?"":`歌词行数不一致：原歌词 ${c[0]} 行，中文 ${c[1]} 行，英文 ${c[2]} 行。请用空行保留对应位置。`},[form.lyrics_original,form.lyrics_zh,form.lyrics_en]);
 useEffect(()=>{if(!id)return;adminFetch<{song:Form}>(`/api/admin/songs/${id}`).then(({song})=>setForm({...blank,...song,extras:song.extras??[]})).catch(e=>setError(e.message))},[id]);
 const set=<K extends keyof Form>(key:K,value:Form[K])=>setForm(old=>({...old,[key]:value}));
 function setExtra(index:number,key:keyof Extra,value:unknown){setForm(old=>({...old,extras:old.extras.map((x,i)=>i===index?{...x,[key]:value}:x)}))}
 async function upload(file:File|undefined,category:string,onDone:(key:string,url:string)=>void,setStatus:(s:string)=>void){if(!file)return;const songRef=form.slug||form.id;if(!songRef){setError("请先填写 slug，再上传文件");return}setStatus("上传中…");setError("");const data=new FormData();data.set("file",file);data.set("category",category);data.set("song_ref",songRef);try{const result=await adminFetch<{key:string;url:string}>("/api/admin/upload",{method:"POST",body:data});onDone(result.key,result.url);setStatus(`已上传：${file.name}`)}catch(e){setStatus("上传失败");setError(e instanceof Error?e.message:"上传失败")}}
 async function save(status:Status){setBusy(true);setError("");setMessage("");try{const payload={...form,status};const result=await adminFetch<{id:string}>(form.id?`/api/admin/songs/${form.id}`:"/api/admin/songs",{method:form.id?"PUT":"POST",body:JSON.stringify(payload)});const savedId=result.id;if(status==="published")await adminFetch(`/api/admin/songs/${savedId}/publish`,{method:"POST"});if(status==="hidden")await adminFetch(`/api/admin/songs/${savedId}/hide`,{method:"POST"});setForm(old=>({...old,id:savedId,status}));setMessage(status==="draft"?"草稿已保存。":status==="published"?"歌曲已发布。":"歌曲已隐藏，数据和文件仍保留。");if(!form.id)history.replaceState(null,"",`?id=${encodeURIComponent(savedId)}`)}catch(e){setError(e instanceof Error?e.message:"保存失败")}finally{setBusy(false)}}
 async function uploadMain(event:ChangeEvent<HTMLInputElement>,category:"cover"|"audio"){const file=event.target.files?.[0];await upload(file,category,(key,url)=>setForm(old=>({...old,[`${category}_key`]:key,[`${category}_url`]:url})),s=>setMessage(s))}
 return <main className="admin-page"><div className="admin-actions"><Link href="/admin/">← 歌曲列表</Link></div><h1>{form.id?"编辑歌曲":"新建歌曲"}</h1>{error&&<p className="admin-message error">{error}</p>}{message&&<p className="admin-message success">{message}</p>}<form className="admin-form" onSubmit={e=>e.preventDefault()}>
 <section className="admin-section"><h2>基本信息</h2><div className="admin-grid"><Field label="slug"><input required value={form.slug} onChange={e=>set("slug",e.target.value)}/></Field><Field label="原始歌名"><input value={form.original_title} onChange={e=>set("original_title",e.target.value)}/></Field><Field label="中文译名"><input value={form.title_zh} onChange={e=>set("title_zh",e.target.value)}/></Field><Field label="英文译名"><input value={form.title_en} onChange={e=>set("title_en",e.target.value)}/></Field><Field label="歌曲语言"><select value={form.language} onChange={e=>set("language",e.target.value as Form["language"])}><option value="">请选择</option><option value="zh">zh</option><option value="en">en</option><option value="mixed">mixed</option></select></Field><Field label="完成日期"><input type="date" value={form.completed_at??""} onChange={e=>set("completed_at",e.target.value)}/></Field><Field label="唱片架顺序"><input type="number" value={form.shelf_order} onChange={e=>set("shelf_order",Number(e.target.value))}/></Field><Field label="状态"><select value={form.status} onChange={e=>set("status",e.target.value as Status)}><option value="draft">draft</option><option value="published">published</option><option value="hidden">hidden</option></select></Field><Field label="中文简介" full><textarea value={form.summary_zh} onChange={e=>set("summary_zh",e.target.value)}/></Field><Field label="英文简介" full><textarea value={form.summary_en} onChange={e=>set("summary_en",e.target.value)}/></Field></div></section>
 <section className="admin-section"><h2>媒体文件</h2><div className="admin-media"><Field label="专辑封面（JPEG / PNG / WebP，最大 10MB）"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>uploadMain(e,"cover")}/><small>{form.cover_key||"尚未上传"}</small>{form.cover_url&&<img src={form.cover_url} alt="封面预览"/>}</Field><Field label="歌曲音频（MP3 / M4A / WAV，最大 100MB）"><input type="file" accept="audio/mpeg,audio/mp4,audio/wav" onChange={e=>uploadMain(e,"audio")}/><small>{form.audio_key||"尚未上传"}</small>{form.audio_url&&<audio controls src={form.audio_url}/>}</Field></div></section>
 <section className="admin-section"><h2>歌词</h2>{lyricWarning&&<p className="admin-message error">{lyricWarning} 草稿仍可保存，发布前必须修正。</p>}<div className="admin-grid admin-lyrics"><Field label={`原歌词（${lineCount(form.lyrics_original)} 行）`}><textarea value={form.lyrics_original} onChange={e=>set("lyrics_original",e.target.value)}/></Field><Field label={`中文翻译（${lineCount(form.lyrics_zh)} 行）`}><textarea value={form.lyrics_zh} onChange={e=>set("lyrics_zh",e.target.value)}/></Field><Field label={`英文翻译（${lineCount(form.lyrics_en)} 行）`}><textarea value={form.lyrics_en} onChange={e=>set("lyrics_en",e.target.value)}/></Field></div></section>
 <section className="admin-section"><h2>制作花絮</h2><button type="button" onClick={()=>set("extras",[...form.extras,newExtra()])}>添加花絮</button>{form.extras.map((extra,index)=><div className="admin-extra" key={extra.id??`new-${index}`}><h3>花絮 {index+1}</h3><div className="admin-grid"><Field label="类型"><select value={extra.type} onChange={e=>setExtra(index,"type",e.target.value)}><option value="text">text</option><option value="image">image</option><option value="audio">audio</option><option value="video">video</option></select></Field><Field label="状态"><select value={extra.status} onChange={e=>setExtra(index,"status",e.target.value)}><option value="draft">draft</option><option value="published">published</option><option value="hidden">hidden</option></select></Field>{extra.type!=="text"&&<Field label="媒体文件"><input type="file" accept={extra.type==="image"?"image/jpeg,image/png,image/webp":extra.type==="audio"?"audio/mpeg,audio/mp4,audio/wav":"video/mp4,video/webm,video/quicktime"} onChange={e=>upload(e.target.files?.[0],extra.type==="audio"?"extra_audio":extra.type,(key,url)=>{setExtra(index,"file_key",key);setExtra(index,"file_url",url)},s=>setExtra(index,"uploadStatus",s))}/><small>{extra.uploadStatus||extra.file_key||"尚未上传"}</small>{extra.file_url&&extra.type==="image"&&<img src={extra.file_url} alt="花絮预览"/>}{extra.file_url&&extra.type==="audio"&&<audio controls src={extra.file_url}/>} {extra.file_url&&extra.type==="video"&&<video controls width="260" src={extra.file_url}/>}</Field>}<Field label="中文标题"><input value={extra.title_zh} onChange={e=>setExtra(index,"title_zh",e.target.value)}/></Field><Field label="英文标题"><input value={extra.title_en} onChange={e=>setExtra(index,"title_en",e.target.value)}/></Field><Field label="中文解说" full><textarea value={extra.caption_zh} onChange={e=>setExtra(index,"caption_zh",e.target.value)}/></Field><Field label="英文解说" full><textarea value={extra.caption_en} onChange={e=>setExtra(index,"caption_en",e.target.value)}/></Field><Field label="日期"><input type="date" value={extra.recorded_at??""} onChange={e=>setExtra(index,"recorded_at",e.target.value)}/></Field><Field label="排序数字"><input type="number" value={extra.sort_order} onChange={e=>setExtra(index,"sort_order",Number(e.target.value))}/></Field></div><div className="admin-actions">{!extra.id&&<button type="button" onClick={()=>set("extras",form.extras.filter((_,i)=>i!==index))}>删除未保存花絮</button>}{extra.id&&<button type="button" onClick={()=>setExtra(index,"status","hidden")}>标记为隐藏</button>}</div></div>)}</section>
 <div className="admin-actions"><button disabled={busy} type="button" onClick={()=>save("draft")}>保存草稿</button><button disabled={busy||!!lyricWarning} type="button" onClick={()=>save("published")}>发布</button><button disabled={busy||!form.id} type="button" onClick={()=>save("hidden")}>隐藏</button>{busy&&<span>处理中…</span>}</div></form><p><small>后台页面本身不包含密码系统；生产写入由 Cloudflare Access 在 Worker 端验证。API：{adminApiBase||"未配置"}</small></p></main>
}
function Field({label,children,full=false}:{label:string;children:React.ReactNode;full?:boolean}){return <label className={`admin-field ${full?"full":""}`}><span>{label}</span>{children}</label>}
